title:             Sevilla Maker Society
description:       La comunidad maker de Sevilla
author:            MakerSocietySVQ
url:               "https://sevillamakers.com"
email:             makersociety.svq@gmail.com
lang:              es_ES
# Seo tag
twitter:
  username: MakerSocietySVQ
  card: summary
facebook:
  publisher: 2058902251011477

logo:               /img/sms-icon.png
# Social Profiles
social:
  links:
    - https://www.twitter.com/MakerSocietySVQ
    - https://www.facebook.com/groups/2058902251011477/
    - https://github.com/maker-society-svq
    - https://www.meetup.com/es-ES/Maker-Society/
    - https://es.linkedin.com/company/makersocietysvq

twitter_username:  MakerSocietySVQ
github_username:   maker-society-svq
facebook_username: groups/2058902251011477/

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  landmarks:
    output: true
  events:
    output: true
future: true
